-- SHOW DATABASES;
-- SHOW TABLES;
USE SGBD;
-- CREATE USER 'nombre_usuario'@'localhost' IDENTIFIED  BY 'contraseña';
-- GRANT USAGE ON *.* TO 'lauracosorio'@'localhost' IDENTIFIED BY 'laura123';
-- GRANT ALL PRIVILEGES ON sgbd.* TO 'lauracosorio'@'localhost' IDENTIFIED BY 'laura123';

USE SGBD;

DROP TABLE IF EXISTS TIPO_DOCUMENTO;
DROP TABLE IF EXISTS TIPO_ACTORES;
DROP TABLE IF EXISTS ESTADO_ACTORES;
DROP TABLE IF EXISTS MODULOS;
DROP TABLE IF EXISTS ACTORES;

CREATE TABLE TIPO_DOCUMENTO(
    CODIGO VARCHAR(3) PRIMARY KEY,
    DESCRIPCION VARCHAR(250) NOT NULL
);

CREATE TABLE TIPO_ACTORES(
    ID INT(5) UNSIGNED PRIMARY  KEY  AUTO_INCREMENT,
    PERFIL VARCHAR(100)
);

CREATE TABLE ESTADO_ACTORES(
    ID INT(5) UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    ESTADO VARCHAR(30)
);

CREATE TABLE MODULOS(
    ID INT(5),
    MODULO VARCHAR(250),
    `MOD` VARCHAR(10)
);

-- ALTER TABLE MODULOS ADD PRIMARY KEY(ID);
ALTER TABLE MODULOS MODIFY ID INT(5) AUTO_INCREMENT PRIMARY KEY ;

CREATE TABLE ACTORES(
    ID INT(5) UNSIGNED  PRIMARY KEY AUTO_INCREMENT ,
    DOCUMENTO VARCHAR(20) NOT NULL UNIQUE,
    TIPO_DOCUMENTO VARCHAR(3) NOT NULL ,
    NOMBRE VARCHAR(250) NOT NULL,
    APELLIDOS VARCHAR(250),
    CONTRASENA VARCHAR(100) NOT NULL,
    CORREO VARCHAR(250) NOT NULL DEFAULT 'correo@dominio.com' ,
    TELEFONO_CELULAR BIGINT(10) UNSIGNED COMMENT 'TELEFONO CELULAR DEL ACTOR',
    NUMERO_EXPEDIENTE VARCHAR(255) NOT NULL UNIQUE,
    GENERO ENUM('FEMENINO', 'MASCULINO', 'OTRO') NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    ESTADO_ACTOR_ID INT(5) UNSIGNED,
    INSTITUCION_ID INT(5),
    TIPO_ACTOR_ID INT(5) UNSIGNED,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FECHA_ACTUALIZACION TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT FK_EA FOREIGN KEY(ESTADO_ACTOR_ID) REFERENCES ESTADO_ACTORES(ID),
    CONSTRAINT FK_TA FOREIGN KEY(TIPO_ACTOR_ID) REFERENCES TIPO_ACTORES(ID)
    
);

INSERT INTO TIPO_ACTORES VALUES(1, 'Alunmo');
INSERT INTO TIPO_ACTORES(PERFIL) VALUES('Docente'),('Cordinador'),('Rector');

SELECT PERFIL, ID, NOW() FROM TIPO_ACTORES;

UPDATE TIPO_ACTORES SET PERFIL = 'Estudiante' WHERE ID = 1;
